export const wiegrad ={
    list:[
        {
            name:"Amuthavalli",
            department:"ECE",
            mid:"99117544"
        },
        {
            name:"Amuthavalli",
            department:"ECE",
            mid:"99117544"
        },
        {
            name:"Amuthavalli",
            department:"ECE",
            mid:"99117544"
        },
        {
            name:"Amuthavalli",
            department:"ECE",
            mid:"99117544"
        },
        {
            name:"Amuthavalli",
            department:"ECE",
            mid:"99117544"
        },
        {
            name:"Amuthavalli",
            department:"ECE",
            mid:"99117544"
        },
        {
            name:"Amuthavalli",
            department:"ECE",
            mid:"99117544"
        },
        {
            name:"Amuthavalli",
            department:"ECE",
            mid:"99117544"
        },
        {
            name:"Amuthavalli",
            department:"ECE",
            mid:"99117544"
        },
        {
            name:"Amuthavalli",
            department:"ECE",
            mid:"99117544"
        },
        {
            name:"Amuthavalli",
            department:"ECE",
            mid:"99117544"
        },
        {
            name:"Amuthavalli",
            department:"ECE",
            mid:"99117544"
        },
        {
            name:"Amuthavalli",
            department:"ECE",
            mid:"99117544"
        },
        {
            name:"Amuthavalli",
            department:"ECE",
            mid:"99117544"
        },
    ]
}